os: osx
sudo: true
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
script:
  - brew install --HEAD hostsblock
  - sudo hostsblock -f test/hostsblock.conf
  - grep localtest test/hosts
  - "! grep -L foo.com test/hosts"
  - echo 1 | sudo hostsblock-urlcheck -f test/hostsblock.conf http://foo.com
  - grep foo.com test/hosts
  - echo 1 | sudo hostsblock-urlcheck -f test/hostsblock.conf http://foo.com
  - "! grep -L foo.com test/hosts"
